title: "Spirit Connect AIPE Labs"
description: "Open power electronics knowledge and design resources for coding agents"
email: "info@spiritconnect.co.uk"
url: "https://aipel.co.uk"
baseurl: ""
timezone: Europe/London

permalink: /resources/blog/:title/

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - .idea
  - .gitignore

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
